### PR TITLE
publish script

### PR DESCRIPTION
**Pull request by stefan-wullems**
I have absolutely no idea what I'm doing

### CODE REVIEW

**Comment by hongaar** [comment]
> I have absolutely no idea what I'm doing

PR approved!

**Comment by hongaar** [comment]
Some helpful notes then. @exivity/ui uses [standard-version](https://github.com/conventional-changelog/standard-version) to determine next version for the package (that's the `yarn bump:version` you're seeing). It then runs npm publish and git push and those sort of things.

I think [semantic-release](https://github.com/semantic-release/semantic-release) might be even more useful though.

**Review by hongaar — COMMENTED** [review]
Ok some helpful notes then.

@exivity/ui uses [standard-version](https://github.com/conventional-changelog/standard-version) to determine next version for the package (that's the `yarn bump:version` you're seeing). It then runs npm publish and git push and those sort of things.

I think [semantic-release](https://github.com/semantic-release/semantic-release) might be even more useful though.

**Comment by stefan-wullems** [comment]
I'll check it out

**Comment by hongaar** [comment]
Attempt at #10

I'll iterate fast on this (merging on the go) as the easiest way of verifying this works is by pushing to master ;)

#yolo

**Pull request closed without merging**
